#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

if [ $# -eq 0 ]
then 
		echo "Usage: fan_control (temp/check/set) (set speed)"
		exit
fi

if [ $1 == temp ]
then
	TMP=$(cat /sys/class/thermal/thermal_zone*/temp)
	echo "${TMP:0:2} Celsius"
	exit
fi

if [ $1 == check ]
then
	SPEED=$(cat /sys/class/thermal/cooling_device0/cur_state)
	echo "Fans are set to mode: $SPEED"
	exit
fi

if [ $1 == set ]
then
	if [ $2 ]
	then
		echo $2 > /sys/class/thermal/cooling_device0/cur_state
		echo $2 > /sys/class/thermal/cooling_device1/cur_state
		echo $2 > /sys/class/thermal/cooling_device2/cur_state
		echo $2 > /sys/class/thermal/cooling_device3/cur_state
		echo $2 > /sys/class/thermal/cooling_device4/cur_state

		echo "Fans mode set to $2"
		exit
	fi
fi
